application: blababeluci
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# this is for loading .css files
- url: /css
  static_dir: css

# this is for loading image files
- url: /img
  static_dir: img

# this is for loading image files
- url: /js
  static_dir: js

# this is for loading lesson files
#- url: /lessons
#  static_dir: lessons


# - url: /_ah/login_required
#   script: do_opened_login.app


- url: /.*
  script: main.application
#  login: required



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

